project:
  type: website
  output-dir: docs

website:
  title: "InterEcoWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: WhyInterEco.qmd
      - text: Why InterEco?
      - href: InterEcoTool.qmd
      - text: InterEco Tool?
      - href: example.qmd
        text: Example

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

