---
title: "Why InterEco?"
---

Ecology\'s central remit is to identify, explain and predict the relationships among the causal threads of life\'s rich tapestry. To achieve this, ecological modelling has vastly increased in complexity over recent decades alongside increases in computing power and availability of \'big data\' from environmental monitoring programmes. Despite these advances, our presentation of model results in scientific publications [has remained relatively unchanged for centuries](https://media.nature.com/original/magazine-assets/d41586-018-01322-9/d41586-018-01322-9.pdf), with scientific figures typically rendered as static, 2D images with a single x and y axis. Such simplistic presentations create missed opportunities for much richer interpretation, can conceal ecological complexity and even lead to erroneous conclusions.
InterEco can overcome these limitations by enabling users to select and directly interact with underlying data and predictions generated by complex models. InterEco has great potential to facilitate nuanced interpretation, improve transparency and increase the impact of ecological research.

**Interpretability**

**Generality**

Originally, sovial sci,

ecologists have recently called for

**Validity**
